//==================================================
// This file contains the Excluded objects
// Generated By User: jhale45
// Format Version: 2
// Date: Fri Sep 19 19:25:48 2025
// ExclMode: default
//==================================================
CHECKSUM: "106343001 1401314186"
INSTANCE: calc_tb_top.my_calc.sram_A
Toggle dout0 "reg dout0[31:0]"
Toggle wmask0_reg "reg wmask0_reg[3:0]"
Toggle wmask0 "net wmask0[3:0]"
CHECKSUM: "106343001 1401314186"
INSTANCE: calc_tb_top.my_calc.sram_B
Toggle dout0 "reg dout0[31:0]"
Toggle wmask0_reg "reg wmask0_reg[3:0]"
Toggle wmask0 "net wmask0[3:0]"
CHECKSUM: "106343001 387058630"
INSTANCE: calc_tb_top.my_calc.sram_A
Block 3 "795780033" "$display($time, \" Reading %m addr0=%b dout0=%b\", addr0_reg, mem[addr0_reg]);"
Block 30 "1258131320" "dout0 <= #(DELAY) mem[addr0_reg];"
Block 13 "3720808073" "$display($time, \" Reading %m addr1=%b dout1=%b\", addr1_reg, mem[addr1_reg]);"
Block 9 "1400422843" "$display($time, \" WARNING: Writing and reading addr0=%b and addr1=%b simultaneously!\", addr0, addr1);"
Block 6 "2498976713" "$display($time, \" Writing %m addr0=%b din0=%b wmask0=%b\", addr0_reg, din0_reg, wmask0_reg);"
CHECKSUM: "106343001 387058630"
INSTANCE: calc_tb_top.my_calc.sram_B
Block 3 "795780033" "$display($time, \" Reading %m addr0=%b dout0=%b\", addr0_reg, mem[addr0_reg]);"
Block 30 "1258131320" "dout0 <= #(DELAY) mem[addr0_reg];"
Block 13 "3720808073" "$display($time, \" Reading %m addr1=%b dout1=%b\", addr1_reg, mem[addr1_reg]);"
Block 9 "1400422843" "$display($time, \" WARNING: Writing and reading addr0=%b and addr1=%b simultaneously!\", addr0, addr1);"
Block 6 "2498976713" "$display($time, \" Writing %m addr0=%b din0=%b wmask0=%b\", addr0_reg, din0_reg, wmask0_reg);"
CHECKSUM: "681465859 2675895518"
INSTANCE: calc_tb_top.my_calc.u_adder.adder
Toggle cin "logic cin"
CHECKSUM: "106343001 4269761601"
INSTANCE: calc_tb_top.my_calc.sram_A
Branch 0 "938286194" "(((!csb0_reg) && web0_reg) && VERBOSE)" (0) "(((!csb0_reg) && web0_reg) && VERBOSE) 1"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (1) "((!csb0_reg) && (!web0_reg)) 1,0,-,-,-"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (7) "((!csb0_reg) && (!web0_reg)) 1,-,-,-,0"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (5) "((!csb0_reg) && (!web0_reg)) 1,-,-,0,-"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (3) "((!csb0_reg) && (!web0_reg)) 1,-,0,-,-"
Branch 3 "1191969408" "((!csb1_reg) && VERBOSE)" (0) "((!csb1_reg) && VERBOSE) 1"
Branch 2 "208107346" "((((!csb0) && (!web0)) && (!csb1)) && (addr0 == addr1))" (0) "((((!csb0) && (!web0)) && (!csb1)) && (addr0 == addr1)) 1"
Branch 1 "17424628" "(((!csb0_reg) && (!web0_reg)) && VERBOSE)" (0) "(((!csb0_reg) && (!web0_reg)) && VERBOSE) 1"
Branch 5 "1867510902" "((!csb0_reg) && web0_reg)" (0) "((!csb0_reg) && web0_reg) 1"
CHECKSUM: "106343001 4269761601"
INSTANCE: calc_tb_top.my_calc.sram_B
Branch 2 "208107346" "((((!csb0) && (!web0)) && (!csb1)) && (addr0 == addr1))" (0) "((((!csb0) && (!web0)) && (!csb1)) && (addr0 == addr1)) 1"
Branch 1 "17424628" "(((!csb0_reg) && (!web0_reg)) && VERBOSE)" (0) "(((!csb0_reg) && (!web0_reg)) && VERBOSE) 1"
Branch 0 "938286194" "(((!csb0_reg) && web0_reg) && VERBOSE)" (0) "(((!csb0_reg) && web0_reg) && VERBOSE) 1"
Branch 5 "1867510902" "((!csb0_reg) && web0_reg)" (0) "((!csb0_reg) && web0_reg) 1"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (1) "((!csb0_reg) && (!web0_reg)) 1,0,-,-,-"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (7) "((!csb0_reg) && (!web0_reg)) 1,-,-,-,0"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (5) "((!csb0_reg) && (!web0_reg)) 1,-,-,0,-"
Branch 4 "2789462054" "((!csb0_reg) && (!web0_reg))" (3) "((!csb0_reg) && (!web0_reg)) 1,-,0,-,-"
Branch 3 "1191969408" "((!csb1_reg) && VERBOSE)" (0) "((!csb1_reg) && VERBOSE) 1"
CHECKSUM: "106343001 616254592"
INSTANCE: calc_tb_top.my_calc.sram_B
Condition 4 "3552763723" "(((!csb0_reg)) && web0_reg) 1 -1" (3 "11")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (1 "0111")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (5 "1111")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (4 "1110")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (3 "1101")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (2 "1011")
Condition 3 "2721236529" "(((!csb0_reg)) && ((!web0_reg))) 1 -1" (2 "10")
Condition 3 "2721236529" "(((!csb0_reg)) && ((!web0_reg))) 1 -1" (1 "01")
CHECKSUM: "106343001 616254592"
INSTANCE: calc_tb_top.my_calc.sram_A
Condition 4 "3552763723" "(((!csb0_reg)) && web0_reg) 1 -1" (3 "11")
Condition 3 "2721236529" "(((!csb0_reg)) && ((!web0_reg))) 1 -1" (1 "01")
Condition 3 "2721236529" "(((!csb0_reg)) && ((!web0_reg))) 1 -1" (2 "10")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (1 "0111")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (2 "1011")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (5 "1111")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (3 "1101")
Condition 1 "1036855301" "(((!csb0)) && ((!web0)) && ((!csb1)) && (addr0 == addr1)) 1 -1" (4 "1110")
